##Setup environment for Mental Health In Tech Dashboard
##conda env create -f environment.yaml

name: 'mentalhealthdashboard'
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  - ipykernel
  - ipython>=7.15
  - gunicorn
  - scipy
  - pandas
  - numpy
  - plotly
  - pip
  - pip:
    - dash
    - dash_bootstrap_components